name: Checks and build for electron

on:
  push:
    branches: [master, development]
    paths-ignore:
      - '.vscode/**'
      - 'README.md'
      - 'LICENSE'
      - 'manifest.json'
  pull_request:
    branches: [master, development]
    paths-ignore:
      - '.vscode/**'
      - 'README.md'
      - 'LICENSE'
      - 'manifest.json'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: yarn install --production=false
    - name: Lint
      run: yarn run lint
  build:
    needs: lint
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        os: [macos-latest, ubuntu-latest, windows-latest]
        experimental: [false]
        include:
          - os: macos-latest
            npmcommand: pkg:darwin
            codename: Darwin
          - os: ubuntu-latest
            npmcommand: pkg:linux
            codename: Linux
          - os: windows-latest
            npmcommand: pkg:win32
            codename: Windows

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - run: yarn install --production=false
    - name: Build/Compile ${{ matrix.codename }}
      run: yarn run build
    - name: Package ${{ matrix.codename }}
      env:
        COMMAND: ${{ matrix.npmcommand }}
      run: yarn run "$COMMAND"
    - name: Upload artifact if node 16
      if: ${{ matrix.node == 16 }}
      uses: actions/upload-artifact@v2
      with:
        name: Electron-${{ matrix.codename }}
        path: out/