name: Checks and build for electron

on:
  push:
    branches: [main, development]
    paths-ignore:
      - '.vscode/**'
      - 'README.md'
      - 'typings.json'
      - 'popupChrome/**'
      - 'indexChrome.js'
      - 'LICENSE'
  pull_request:
    branches: [main, development]
    paths-ignore:
      - '.vscode/**'
      - 'README.md'
      - 'typings.json'
      - 'popupChrome/**'
      - 'indexChrome.js'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install --production=false
    - name: Lint
      run: npm run lint --if-present
  build:
    needs: lint
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16]
        os: [macos-latest, ubuntu-latest, windows-latest]
        experimental: [false]
        include:
          - os: macos-latest
            npmcommand: build-darwin
          - os: ubuntu-latest
            npmcommand: build-linux
          - os: windows-latest
            npmcommand: build-win32

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - run: npm install --production=false
    - name: Build ${{ matrix.npmcommand }}
      env:
        COMMAND: ${{ matrix.npmcommand }}
      run: npm run $COMMAND --if-present
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Electron-${{ matrix.npmcommand }}
        path: out/